### PR TITLE
frontend/fix #1786 latency pop and remove notification solved

### LINKED ISSUE #1786: Latencies remove notification race condition
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**App (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by KiranBKL**
## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

### CODE REVIEW

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java [hunk 1]
```diff
@@ -95,6 +86,7 @@ public class NotificationUtils extends AppCompatActivity {
     private static boolean hasStartedService = false;
     public static OverlaySheetService.OverlayBinder binder;
     public static ArrayList<Bundle> listData = new ArrayList();
+    public static ArrayList<String> removeList = new ArrayList<>();
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java:89]: can we not rely on static variable for this if values are getting restored after killing and opening the app

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java [hunk 2]
```diff
@@ -342,10 +344,19 @@ public void onServiceDisconnected(ComponentName name) {
...
             if (notificationType.equals(context.getString(R.string.CLEARED_FARE)) || notificationType.equals(context.getString(R.string.CANCELLED_SEARCH_REQUEST))){
+                System.out.println("cleared fare "+context.getString((R.string.CLEARED_FARE)));
                 if (binder !=null){
-                    binder.getService().removeCardById(data.getString(context.getString(R.string.entity_ids)));
+                    System.out.println("Check Entity id cleared:- "+data.getString("entity_ids"));
+                    if (binder.getService().removeCardById(data.getString(context.getString(R.string.entity_ids))))
+                    {
+                        System.out.println("Check Entity id cleared:- 1"+data.getString(context.getString(R.string.entity_ids)));
+
+                    }
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java:355]: remove this

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java [hunk 3]
```diff
@@ -342,10 +344,19 @@ public void onServiceDisconnected(ComponentName name) {
                 }
                 notificationId ++;
             }
-
             if (notificationType.equals(context.getString(R.string.CLEARED_FARE)) || notificationType.equals(context.getString(R.string.CANCELLED_SEARCH_REQUEST))){
+                System.out.println("cleared fare "+context.getString((R.string.CLEARED_FARE)));
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java:348]: remove logs

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java [hunk 4]
```diff
@@ -255,8 +251,14 @@ public static void showAllocationNotification (Context context, String title, St
...
-                            context.startService(svcT);
-                            listData.add(sheetData);
+
+                            new Handler(context.getMainLooper()).postDelayed(new Runnable() {
+                                @Override
+                                public void run() {
+                                    context.startService(svcT);
+                                    listData.add(sheetData);
+                                }
+                            },0000);
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java:261]: not required

**Review by ashishsingh101 — CHANGES_REQUESTED** [review]

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java [hunk 5]
```diff
@@ -189,11 +184,36 @@ public static Notification createNotification (Context context, String title, St
...
             String channelId;
-            if (ALLOCATION_TYPE.equals(notificationType)) {
-                System.out.println("showNotification:- "+ notificationType);
+            SharedPreferences sharedRemovePref = context.getSharedPreferences(
+                    context.getString(R.string.removeNotification), Context.MODE_PRIVATE);
+       //     if(ALLOCATION_TYPE.equals(notificationType) && removeList.containsKey(data.getString("entity_ids")))
+         //   {
+          //      removeList.remove(data.getString("entity_ids"));
+           //     return;
+            //}
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java:199]: remove commented codes

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestUtils.java [hunk 6]
```diff
@@ -154,6 +154,26 @@ public int calculateExpireTimer(String expireTimeTemp, String currTimeTemp){
         if ((expireTime-currTime) > 0) return expireTime-currTime;
         return 0;
     }
+    public int calculateExpireTimerForMinutes(String expireTimeTemp, String currTimeTemp){
+        if (expireTimeTemp == null || currTimeTemp == null) return 0;
+        String[] arrOfA = expireTimeTemp.split("T");//2023-07-20T022:45:16.168244Z
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestUtils.java:159]: remove commented codes

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java (hunk 5 above)
Comment (ashishsingh101) [reply Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java:199]: other places as well

**Review by ashishsingh101 — CHANGES_REQUESTED** [review]

**Comment by KiranBKL** [comment]
I have solved using shared pref, could you have look that once in latest commit

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java [hunk 7]
```diff
@@ -95,6 +89,7 @@ public class NotificationUtils extends AppCompatActivity {
     private static boolean hasStartedService = false;
     public static OverlaySheetService.OverlayBinder binder;
     public static ArrayList<Bundle> listData = new ArrayList();
+    public static Map<String,String> removeList = new HashMap<>();
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java:92]: remove this if not required

**Review by ashishsingh101 — CHANGES_REQUESTED** [review]

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java [hunk 8]
```diff
@@ -189,11 +184,36 @@ public static Notification createNotification (Context context, String title, St
...
         try{
+
+            final SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",new Locale("en","US"));
+            f.setTimeZone(TimeZone.getTimeZone("IST"));
+            String currTime = f.format(new Date());
             String notificationType = new String(data.getString("notification_type"));
             String channelId;
-            if (ALLOCATION_TYPE.equals(notificationType)) {
-                System.out.println("showNotification:- "+ notificationType);
+            SharedPreferences sharedRemovePref = context.getSharedPreferences(
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java:193]: @KiranBKL you can use static also since its independent of activity, you can revert your changes and squash

**Review by ashishsingh101 — CHANGES_REQUESTED** [review]

File: Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestUtils.java [hunk 9]
```diff
@@ -154,6 +154,26 @@ public int calculateExpireTimer(String expireTimeTemp, String currTimeTemp){
         if ((expireTime-currTime) > 0) return expireTime-currTime;
         return 0;
     }
+    public int calculateExpireTimerForMinutes(String expireTimeTemp, String currTimeTemp){
+        if (expireTimeTemp == null || currTimeTemp == null) return 0;
+        String[] arrOfA = expireTimeTemp.split("T");
+        String[] arrOfB = currTimeTemp.split("T");
```
Comment (ashishsingh101) [inline Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestUtils.java:160]: use proper variable name

Comment (ashishsingh101) [reply Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestUtils.java:160]: instead of seperating with `T` can't we fetch time directly ?

**Review by ashishsingh101 — CHANGES_REQUESTED** [review]

**Review by Vignesh-772 — APPROVED** [review]

**Review by ashishsingh101 — APPROVED** [review]
